name: 'Install packages'
description: 'Install required packages'

runs:
  using: "composite"
  steps:
    # Common Linux dependencies
    - name: Install Linux Dependencies
      shell: bash
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common ninja-build
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-14 g++-14
        
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 19 all

    - name: Install valgrind
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_valgrind == true
      run: |
        # sudo apt-get update
        sudo apt-get install --no-install-recommends valgrind
